navigation: add missing action
-- without this an action from searchbar to search result page results in crash

java.lang.IllegalArgumentException: Navigation action/destination com.aurora.store.debug:id/action_searchSuggestionFragment_to_searchResultsFragment cannot be found from the current destination Destination(com.aurora.store.debug:id/searchResultsFragment) label=Search results class=com.aurora.store.view.ui.search.SearchResultsFragment